### PR TITLE
fix: include fieldless variants in is_x, allow creating fieldless variants

### LINKED ISSUE #15: `py_wrap_union_enum!` doesn't generate correct code for checking against fieldless variants
Consider the following enum definition:

```rs
enum MyEnum {
    A
}

py_wrap_union_enum! {
    PyMyEnum(MyEnum) {
        a: A
    }
}
```

The following code gets generated for `is_a`

```rs
    const fn is_a(&self) -> bool {
        match &self.0 {
            _ => false,
        }
    }
```

As defined by the macro, `is_a` will always return false.

It looks like the macro doesn't consider fieldless variants for this method, since the branch arm that gets generated always includes `(_)`: https://github.com/rigetti/rigetti-pyo3/blob/main/src/wrappers.rs#L628C5-L639

### PR DESCRIPTION
**Pull request by Shadow53**
Resolves #15.

This modifies the `py_wrap_union_enum` macro in two ways:

1. `is_x` now works correctly for fieldless variants.
2. Unitless variants get a `new_x` method generated for them as a counterpart to `from_x`. This was added in part because it was missing and in part to be able to test (1).

Any `pyi` files in dependent projects using union enums with fieldless variants will need to be updated to include the `new_x` methods.

### CODE REVIEW

File: src/wrappers.rs [hunk 1]
```diff
@@ -580,6 +625,10 @@ macro_rules! py_wrap_union_enum {
 
         $crate::impl_as_mut_for_wrapper!($name);
 
+        $(
+        $crate::py_wrap_union_enum!(@from $name, $rs_inner, $variant_name, $variant $($(=> $convert)+)?);
+        )+
+
         $crate::paste::paste! {
         #[$crate::pyo3::pymethods]
         impl $name {
```
Comment (jselig-rigetti) [inline src/wrappers.rs:634]: Not a blocker, but how does `#[new]` (line 636) work with fieldless variants?

Also, I'm having trouble running the tests locally with `cargo make test`:

```
dyld[38322]: Library not loaded: @rpath/libpython3.9.dylib
```

**Review by jselig-rigetti — APPROVED** [review]
Overall LGTM, might want to mark as a breaking change due to `from_unit` -> `new_unit` rename, unless the prior method never worked in the first place

File: src/wrappers.rs [hunk 2]
```diff
@@ -580,6 +625,10 @@ macro_rules! py_wrap_union_enum {
 
         $crate::impl_as_mut_for_wrapper!($name);
 
+        $(
+        $crate::py_wrap_union_enum!(@from $name, $rs_inner, $variant_name, $variant $($(=> $convert)+)?);
```
Comment (MarquessV) [inline src/wrappers.rs:629]: recursive macros!

**Review by MarquessV — APPROVED** [review]
This solves the problem that prompted the issue for me. I also ran the execution data tests in `qcs-sdk-rust` against this branch since they make decent use of the methods these macros generate and all was fine!

File: src/wrappers.rs (hunk 2 above)
Comment (Shadow53) [reply src/wrappers.rs:629]: Recursive macros with *internal rules* ;)

File: src/wrappers.rs (hunk 1 above)
Comment (Shadow53) [reply src/wrappers.rs:634]: I had to do a `cargo clean` in order to get tests to compile. I think something gets cached that shouldn't be, but I don't know what.

**Comment by Shadow53** [comment]
> Overall LGTM, might want to mark as a breaking change due to `from_unit` -> `new_unit` rename, unless the prior method never worked in the first place

The prior method never existed. `from_x` was generated at the level where `=> type` was specified at least once, which it's not for unit types.

File: src/wrappers.rs (hunk 1 above)
Comment (Shadow53) [reply src/wrappers.rs:634]: > Not a blocker, but how does #[new] (line 636) work with fieldless variants?

It doesn't :/ The `#[new]` only works for variants with associated data, which is why `new_unit` needed to be added.
